apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "openldap-bitnami.fullname" . }}
  labels:
    {{- include "openldap-bitnami.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{- include "openldap-bitnami.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "openldap-bitnami.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "openldap-bitnami.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: LDAP_SKIP_DEFAULT_TREE
          {{- if .Values.skip_default_tree_generation }}
              value: 'yes'
          {{- else }}
              value: 'no'
          {{- end }}
          {{- if not .Values.tls_enabled }}
            - name: LDAP_ENABLE_TLS
              value: 'no'
          {{- end }}
          {{- if .Values.tls_certificates_from_secret.enabled }}
            - name: LDAP_ENABLE_TLS
              value: 'yes'
            - name: LDAP_TLS_CERT_FILE
              value: '/etc/ssl/private/tls.crt'
            - name: LDAP_TLS_KEY_FILE
              value: '/etc/ssl/private/tls.key'
            - name: LDAP_TLS_CA_FILE
              value: '/etc/ssl/private/tls.crt'
          {{- end }}
          {{- if .Values.envFrom }}
          envFrom:
          {{- with .Values.envFrom }}
          {{- toYaml . | nindent 10 }}
          {{- end }}
          {{- end }}
          ports:
            - name: ldap-tcp
              containerPort: 1389
              protocol: TCP
            - name: ldap-udp
              containerPort: 1389
              protocol: UDP
            - name: ldaps-tcp
              containerPort: 1636
              protocol: TCP
            - name: ldaps-udp
              containerPort: 1636
              protocol: UDP
          volumeMounts:
          - name: {{ .Release.Name }}-database
            mountPath: '/bitnami/openldap/data'
          {{- if .Values.tls_certificates_from_secret.enabled }}
          - name: {{ .Release.Name }}-certs
            mountPath: '/etc/ssl/private/'
          {{- end }}
          livenessProbe:
            tcpSocket:
              port: 1389
            initialDelaySeconds: 15
            periodSeconds: 15
          readinessProbe:
            tcpSocket:
              port: 1389
            initialDelaySeconds: 15
            periodSeconds: 15
          startupProbe:
            tcpSocket:
              port: 1389
            failureThreshold: 12
            periodSeconds: 10
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
      - name: {{ .Release.Name }}-database
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}-database
      {{- if .Values.tls_certificates_from_secret.enabled -}}
      {{- if .Values.tls_certificates_from_secret.generate_certificate }}
      - name: {{ .Release.Name }}-certs
        secret:
          secretName: {{ .Values.tls_certificates_from_secret.certificate.secretName }}
      {{- end }}
      {{- if .Values.tls_certificates_from_secret.existingSecret }}
      - name: {{ .Release.Name }}-certs
        secret:
          secretName: {{ .Values.tls_certificates_from_secret.existingSecret.name }}
      {{- end }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
