apiVersion: v2
name: openldap-bitnami
description: DEPRECATED - Helm chart for OpenLDAP based on the Bitnami image
type: application
version: 2.0.0
deprecated: true
appVersion: 2.6.6
# maintainers:
#   - name: johanneskastl
#     email: git@johannes-kastl.de
